import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import AppHeader from "@/components/app-header/AppHeader";

const popins = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={popins.className}>
        <AppHeader />
        <div className="app__content">{children}</div>
      </body>
    </html>
  );
}
